version: '2'

services:
  remark:
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "127.0.0.1:${PORT_EXTERNAL}:8080"

    env_file:
      - .env

    volumes:
      - ./remark42_storage:/srv/var
