---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: English
- type: directory
  path: content/writing
  label: Writing
  create: all
  match: "**/*.en.md"
  new_doc_ext: en.md
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*.en.md"
  new_doc_ext: en.md
- type: directory
  path: content/photos
  label: Photos
  create: all
  match: "**/*.en.md"
  new_doc_ext: en.md
- type: heading
  label: Deutsch
- type: directory
  path: content/writing
  label: Schrift
  create: all
  match: "**/*.de.md"
  new_doc_ext: de.md
- type: directory
  path: content/projects
  label: Projekte
  create: all
  match: "**/*.de.md"
  new_doc_ext: de.md
- type: directory
  path: content/photos
  label: Fotos
  create: all
  match: "**/*.de.md"
  new_doc_ext: de.md
- type: heading
  label: Русский
- type: directory
  path: content/writing
  label: Блог
  create: all
  match: "**/*.ru.md"
  new_doc_ext: ru.md
- type: directory
  path: content/projects
  label: Проекты
  create: all
  match: "**/*.ru.md"
  new_doc_ext: ru.md
- type: directory
  path: content/photos
  label: Фото
  create: all
  match: "**/*.ru.md"
  new_doc_ext: ru.md
upload_dir: static/self
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
